name: todo_app_v2
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^10.8.5
  intl: ^0.19.0
  quill_native_bridge: ^10.7.11
  todo_db_api:
    path: packages/todo_db_api
  todos_repository:
    path: packages/todos_repository
  
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

fonts:
  - family: Fixel
    fonts:
      - asset: assets/fonts/FixelVariable.ttf
      - asset: assets/fonts/FixelVariableItalic.ttf
        style: italic
