name: todo_app_v2
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  background_fetch: ^1.3.7
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^10.8.5
  intl: ^0.19.0
  quill_native_bridge: ^10.7.11
  shared_preferences: ^2.5.2
  table_calendar: ^3.1.3
  timezone: ^0.10.0
  todo_db_api:
    path: packages/todo_db_api
  todos_repository:
    path: packages/todos_repository
  uuid: ^4.5.1

dependency_overrides:
  http: 1.3.0
  
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ">=1.24.0 <1.25.9"
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

fonts:
  - family: Fixel
    fonts:
      - asset: assets/fonts/FixelVariable.ttf
      - asset: assets/fonts/FixelVariableItalic.ttf
        style: italic

